<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7abe16129b21a9417f37ae4355c95f8e
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7abe16129b21a9417f37ae4355c95f8e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7abe16129b21a9417f37ae4355c95f8e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
